// AUTH

export const INICIO_SESION_REQUEST = 'INICIO_SESION_REQUEST';
export const INICIO_SESION_EXITOSO = 'INICIO_SESION_EXITOSO';
export const INICIO_SESION_FALLIDO = 'INICIO_SESION_FALLIDO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const CARGAR_DATOS_USUARIO_REQUEST = 'CARGAR_DATOS_USUARIO_REQUEST';
export const CARGAR_DATOS_USUARIO_EXITOSO = 'CARGAR_DATOS_USUARIO_EXITOSO';
export const CARGAR_DATOS_USUARIO_FALLIDO = 'CARGAR_DATOS_USUARIO_FALLIDO';
export const BORRAR_DATOS_USUARIO = 'BORRAR_DATOS_USUARIO';

// USUARIO ADMINISTRATIVO

// materias
export const FETCH_MATERIAS_REQUEST = 'FETCH_MATERIAS_REQUEST';
export const FETCH_MATERIAS_EXITOSO = 'FETCH_MATERIAS_EXITOSO';
export const FETCH_MATERIAS_FALLIDO = 'FETCH_MATERIAS_FALLIDO';

export const GUARDAR_MATERIA_REQUEST = 'GUARDAR_MATERIA_REQUEST';
export const GUARDAR_MATERIA_EXITOSO = 'GUARDAR_MATERIA_EXITOSO';
export const GUARDAR_MATERIA_FALLIDO = 'GUARDAR_MATERIA_FALLIDO';

export const ESTABLECER_MENSAJE = 'ESTABLECER_MENSAJE';
export const BORRAR_MENSAJE = 'BORRAR_MENSAJE';
