// AUTH

export const INICIO_SESION_REQUEST = 'INICIO_SESION_REQUEST';
export const INICIO_SESION_EXITOSO = 'INICIO_SESION_EXITOSO';
export const INICIO_SESION_FALLIDO = 'INICIO_SESION_FALLIDO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const CARGAR_DATOS_USUARIO_REQUEST = 'CARGAR_DATOS_USUARIO_REQUEST';
export const CARGAR_DATOS_USUARIO_EXITOSO = 'CARGAR_DATOS_USUARIO_EXITOSO';
export const CARGAR_DATOS_USUARIO_FALLIDO = 'CARGAR_DATOS_USUARIO_FALLIDO';
export const BORRAR_DATOS_USUARIO = 'BORRAR_DATOS_USUARIO';

// USUARIO ADMINISTRATIVO

// materias GET
export const FETCH_MATERIAS_REQUEST = 'FETCH_MATERIAS_REQUEST';
export const FETCH_MATERIAS_EXITOSO = 'FETCH_MATERIAS_EXITOSO';
export const FETCH_MATERIAS_FALLIDO = 'FETCH_MATERIAS_FALLIDO';

// materias POST
export const GUARDAR_MATERIA_REQUEST = 'GUARDAR_MATERIA_REQUEST';
export const GUARDAR_MATERIA_EXITOSO = 'GUARDAR_MATERIA_EXITOSO';
export const GUARDAR_MATERIA_FALLIDO = 'GUARDAR_MATERIA_FALLIDO';

// materias PUT
export const EDITAR_MATERIA_REQUEST = 'EDITAR_MATERIA_REQUEST';
export const EDITAR_MATERIA_EXITOSO = 'EDITAR_MATERIA_EXITOSO';
export const EDITAR_MATERIA_FALLIDO = 'EDITAR_MATERIA_FALLIDO';

// materias PATCH
export const ACTIVAR_MATERIA_REQUEST = ' ACTIVAR_MATERIA_REQUEST';
export const ACTIVAR_MATERIA_EXITOSO = ' ACTIVAR_MATERIA_EXITOSO';
export const ACTIVAR_MATERIA_FALLIDO = ' ACTIVAR_MATERIA_FALLIDO';

// materias DELETE
export const DESACTIVAR_MATERIA_REQUEST = ' DESACTIVAR_MATERIA_REQUEST';
export const DESACTIVAR_MATERIA_EXITOSO = ' DESACTIVAR_MATERIA_EXITOSO';
export const DESACTIVAR_MATERIA_FALLIDO = ' DESACTIVAR_MATERIA_FALLIDO';

// usuarios GET
export const GET_USUARIOS_REQUEST = 'GET_USUARIOS_REQUEST';
export const GET_USUARIOS_EXITOSO = 'GET_USUARIOS_EXITOSO';
export const GET_USUARIOS_FALLIDO = 'GET_USUARIOS_FALLIDO';

// carreras GET
export const GET_CARRERAS_REQUEST = 'GET_CARRERAS_REQUEST';
export const GET_CARRERAS_EXITOSO = 'GET_CARRERAS_EXITOSO';
export const GET_CARRERAS_FALLIDO = 'GET_CARRERAS_FALLIDO';

// usuarios POST
export const GUARDAR_USUARIO_REQUEST = 'GUARDAR_USUARIO_REQUEST';
export const GUARDAR_USUARIO_EXITOSO = 'GUARDAR_USUARIO_EXITOSO';
export const GUARDAR_USUARIO_FALLIDO = 'GUARDAR_USUARIO_FALLIDO';

export const ESTABLECER_MENSAJE = 'ESTABLECER_MENSAJE';
export const BORRAR_MENSAJE = 'BORRAR_MENSAJE';
